Repository puppetlabs/puppetlabs-panos, pull requests merged in 2019-04, with the labels that each got.

#82 (FM-7971) backwards compatibility with PE 2019.0
  .sync.yml
  .travis.yml
  Gemfile
  README.md
  lib/puppet/util/network_device/panos/device.rb
  lib/puppet/util/task_helper.rb
  lib/puppet_x/puppetlabs/panos/transport_shim.rb
  spec/spec_helper_local.rb
  spec/unit/puppet/util/task_helper_spec.rb
  tasks/apikey.json
  tasks/commit.json
  tasks/set_config.json
Labels: bugfix

#83 (maint) updating the ssl_fingerprint to accept spaced and colon SHA25…
  lib/puppet/transport/panos.rb
  lib/puppet/transport/schema/panos.rb
Labels: bugfix

#80 (FM-7973) Adding hands on labs for bolt and puppet device
  README.md
  docs/01-using-with-bolt/01-install-prerequisites/README.md
  docs/01-using-with-bolt/02-download-panos-module/README.md
  docs/01-using-with-bolt/03-update-bolt-inventory/README.md
  docs/01-using-with-bolt/04-running-a-task/README.md
  docs/01-using-with-bolt/05-applying-a-manifest/README.md
  docs/01-using-with-bolt/README.md
  docs/02-using-with-puppet-device/01-install-prerequisites/README.md
  docs/02-using-with-puppet-device/02-install-panos-module/README.md
  docs/02-using-with-puppet-device/03-configure-puppet-device/README.md
  docs/02-using-with-puppet-device/04-sign-the-cert/README.md
  docs/02-using-with-puppet-device/05-run-puppet-device-commands/README.md
  docs/02-using-with-puppet-device/README.md
  docs/README.md
Labels: feature

#86 (MODULES-8998) - 1.1.0 Merge Back
  CHANGELOG.md
  REFERENCE.md
  metadata.json
Labels: maintenance
