Repository puppetlabs/puppetlabs-panos, pull requests merged in 2020-12, with the labels that each got.

#123 (IAC-999) - Removal of inappropriate terminology
  .sync.yml
  .travis.yml
  Gemfile
  README.md
  REFERENCE.md
  manifests/install.pp
  manifests/install/server.pp
  manifests/server.pp
  metadata.json
Labels: backwards-incompatible

#125 pdksync - (feat) Add support for Puppet 7
  metadata.json
Labels: feature

#124 pdksync - Update pdk-templates for gitpod and codespaces support
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .gitpod.Dockerfile
  .gitpod.yml
  .pdkignore
  .rubocop.yml
  .sync.yml
  Gemfile
  data/common.yaml
  hiera.yaml
Labels: maintenance
